version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: prod_db
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - "./db-data/mongodb/:/data/db"

volumes:
  mongodb_data: